# Set the maximum line length to 120 characters
max_line_length: 120

# Indent with 4 spaces
indent_size: 4

# Use Unix-style line endings
end_of_line: lf

# Enforce the Kotlin coding style
kotlin_style: "official"